CREATE TABLE "users" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(35) NOT NULL,
  "password" varchar(20) NOT NULL,
  "age" integer NOT NULL,
  "user_type_id" integer NOT NULL
);

CREATE TABLE "courses" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40) NOT NULL,
  "description" varchar(50) NOT NULL,
  "level_id" integer NOT NULL,
  "teacher_id" integer NOT NULL
);

CREATE TABLE "levels" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(10) NOT NULL
);

CREATE TABLE "teachers" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_id" integer NOT NULL
);

CREATE TABLE "courses_videos" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40) NOT NULL,
  "url" varchar(100) NOT NULL,
  "course_id" integer NOT NULL
);

CREATE TABLE "categories" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "user_type" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(15) NOT NULL
);

CREATE TABLE "courses_categories" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer NOT NULL,
  "course_id" integer NOT NULL
);

ALTER TABLE "teachers" ADD FOREIGN KEY ("name_id") REFERENCES "users" ("ID");

ALTER TABLE "users" ADD FOREIGN KEY ("user_type_id") REFERENCES "user_type" ("ID");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("ID");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("ID");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("ID");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("ID");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("ID");

==========

INSERT INTO levels (name) VALUES ('Begginer'), ('Middle'), ('Advance');

INSERT INTO user_type (type) VALUES ('Admin'), ('Teacher'), ('Student');

INSERT INTO categories (name) VALUES ('Frontend'), ('Backend');

INSERT INTO users (name, email, password, age, user_type_id) VALUES ('Juan Mendez', 'j_mendez@gmail.com', 'jm_1234', 35, 2), ('Luis Escalona', 'l_escalona@hotmail.com', 'le_1234', 24, 3), ('Angel Diaz', 'a_diaz@live.es', 'ad_1234', 19, 3), ('Pedro Bocanegra', 'p_bocanegra@gmail.com', 'pb_1234', 36, 2), ('Guillermo Ortega', 'guillermo.ortega@yahoo.com', 'go_1234', 46, 1);

INSERT INTO teachers (name_id) VALUES (1), (4);

INSERT INTO courses (title, description, level_id, teacher_id) VALUES ('HTML5', 'Create structures for Web Sites', 1, 1), ('CSS3', 'Styling Web Sites', 1, 1), ('Javascript Vanilla', 'Funtionality to Web Sites', 1, 1), ('React', 'Advance funtionality of JS', 2, 2), ('Node', 'Backend funtionality', 3, 2);

INSERT INTO courses_videos (title, url, course_id) VALUES ('Commands for HTML', 'url 1', 1), ('Commands for CSSS', 'url 2', 2), ('Commands for Javascript', 'url 3', 3), ('Commands for React', 'url 4', 4), ('Commands for Node', 'url 5', 5);






